[workspace]
resolver = "2"
members = [
    "crates/sp_core",
    "crates/sp_server",
    "crates/sp_cli",
]

[workspace.package]
version = "5.0.0"
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://github.com/audiflow/audiflow-smartplaylist-editor"

[workspace.dependencies]
sp_core = { package = "audiflow-smartplaylist-core", path = "crates/sp_core", version = "5.0.0" }
sp_server = { package = "audiflow-smartplaylist-server", path = "crates/sp_server", version = "5.0.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
